name: Publish Python Package to PyPI

on:
  release:
    types:
      - published  # Trigger the action when a release is published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Install required tools

      - name: Build the package
        run: python setup.py sdist bdist_wheel  # Build the package

      - name: Upload to PyPI
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
